### ISSUE TITLE
Reported issue of… stale sessions causing problems

### ISSUE THREAD

**Issue by wsanchez** [burningmantech/ranger-ims-server#218] opened 2017-09-29 16:19 UTC
Report: "Browser would get confused when old tabs opened by a different user would get reused by the current user. Closing/restarting the browser would correct the issue."

**Comment by wsanchez** [comment] 2017-09-29 16:19
Next step here is to see if we can reproduce this or something similar.

**Comment by srabraham** [comment] 2024-11-24 05:24
The issue is still present, and I see it pretty often after restarting my local IMS server. I'm fairly sure the problem is that a stale TWISTED_SESSION value can continue being used even after logging in via a new tab, and that leads to the issue.

https://github.com/burningmantech/ranger-ims-server/issues/1363

**Comment by srabraham** [comment] 2024-12-15 13:09
should be fixed by https://github.com/burningmantech/ranger-ims-server/pull/1456

**Closed by srabraham** 2024-12-15 13:09 UTC
Labels: Bug, Bite Sized
