### ISSUE TITLE
creating a new incident and then attaching incident to it yields error message

### ISSUE THREAD

**Issue by corprew** [burningmantech/ranger-ims-server#97] opened 2016-08-02 17:28 UTC
![image](https://cloud.githubusercontent.com/assets/56199/17338318/dc8441d6-589b-11e6-8d2e-f71d563841ba.png)

**Comment by corprew** [comment] 2016-08-02 17:33
then after i created an incident report of my own i was able to add both that and the existing IR.

![image](https://cloud.githubusercontent.com/assets/56199/17338516/87162f88-589c-11e6-9c9b-a6c9d270e5d0.png)

**Comment by wsanchez** [comment] 2016-08-03 03:10
@corprew Which server are you banging on?

I've seen this before, usually accompanied by an exception on the server caused by a unique constraint failure on the SQL DB.  I think what's going on in that case is that the (JavaScript) client is attempting to attach the same incident a second time, either because it showed you an unattached incident that was in fact already attached, or something similar.

I see no such exceptions on the demo server (`khaki-shack`), though.

**Comment by wsanchez** [comment] 2016-08-03 03:12
Though… "Bad Request" in the dialog indicates the server disliked the request itself…

**Comment by corprew** [comment] 2016-08-03 03:14
@wsanchez i was on the demo server.

**Comment by corprew** [comment] 2016-08-03 03:25
I just repro'd it again.  It does seem like it only happens immediately after creating a new incident, and then when you close it and re-open the incident, it works.

![image](https://cloud.githubusercontent.com/assets/56199/17352858/4168213c-58ef-11e6-9613-db554f9bf1e1.png)

**Comment by wsanchez** [comment] 2016-08-09 22:34
OK, two things going on here that break this.

 1. The global variable `incidentNumber` is set at page load and not updated when the incident is edited.  So it'll try to attach to an incident number of `null`, which is invalid.

 2. Even if the above is fixed, attempting to attach to a new incident window *before editing anything else* (that is, before the incident is created on the server), then there is no incident to attach to yet, so this will still fail.

**Comment by wsanchez** [comment] 2016-08-09 22:35
First item above fixed with 9d77ae0cf591c5ae06e8d8822f93c47e0dc0994a.

**Comment by wsanchez** [comment] 2016-08-09 22:40
Second with 1dea7d38c889f10de03007c03d39b7aa564a2064.

**Closed by wsanchez** 2016-08-09 22:40 UTC
Labels: Bug
